import { useEffect, useState } from "react";

export default function ProjectIdeasCard({ data }) {
  const [visible, setVisible] = useState(false);
  const ideas = data.ai?.projectIdeas || [
    { title: "Next-Gen CLI Tool", desc: "Build a blazing fast terminal utility using your core tech stack to automate your most annoying daily workflows." },
    { title: "AI-Powered Micro SaaS", desc: "Leverage your backend skills to build a hyper-focused SaaS API wrapping LLM functionality for a niche problem." },
    { title: "Personal Analytics Dashboard", desc: "Scrape your own behavioral data to build a sleek data visualization platform mapping your habits." }
  ];

  useEffect(() => { const t = setTimeout(() => setVisible(true), 50); return () => clearTimeout(t); }, []);

  return (
    <div style={{ ...s.card, opacity: visible ? 1:0, transform: visible ? "scale(1)":"scale(0.95)", transition: "all 0.6s cubic-bezier(0.175, 0.885, 0.32, 1.275)" }}>
      <p style={s.eyebrow}>AI Brainstorm Engine</p>
      <h3 style={s.header}>Your Next {data.year + 1} Projects</h3>
      
      <div style={s.listWrap}>
         {ideas.map((idea, i) => (
            <div key={i} style={s.ideaRow}>
               <div style={s.numberBullet}>{i + 1}</div>
               <div style={s.ideaTextCol}>
                  <h4 style={s.ideaTitle}>{idea.title}</h4>
                  <p style={s.ideaDesc}>{idea.desc}</p>
               </div>
            </div>
         ))}
      </div>
      
      <p style={s.footer}>Generated by scanning your actual commit payloads and topological language stacks.</p>
    </div>
  );
}

const s = {
  card: { width: "100%", maxWidth: 420, minHeight: 400, background: "#0a0c10", border: "1px solid rgba(244, 63, 94, 0.2)", borderRadius: 24, padding: "24px 24px 32px", display: "flex", flexDirection: "column" },
  eyebrow: { margin: "0 0 8px", fontSize: 13, color: "#f43f5e", fontFamily: "'DM Mono', monospace", textTransform: "uppercase", letterSpacing: "0.1em", fontWeight: 700 },
  header: { margin: "0 0 24px", fontSize: 24, color: "#fff", fontFamily: "'Syne', sans-serif", fontWeight: 800, letterSpacing: "-0.02em" },
  listWrap: { flex: 1, display: "flex", flexDirection: "column", gap: 16 },
  ideaRow: { display: "flex", gap: 16, background: "rgba(244, 63, 94, 0.04)", padding: "16px", borderRadius: 16, alignItems: "flex-start", border: "1px solid rgba(244, 63, 94, 0.08)" },
  numberBullet: { width: 28, height: 28, borderRadius: "50%", background: "#f43f5e", color: "#000", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontFamily: "'Syne', sans-serif", fontWeight: 800, flexShrink: 0, marginTop: 2 },
  ideaTextCol: { display: "flex", flexDirection: "column", gap: 6 },
  ideaTitle: { fontSize: 16, color: "#fff", fontFamily: "'Syne', sans-serif", fontWeight: 800, margin: 0, letterSpacing: "-0.01em" },
  ideaDesc: { fontSize: 12, color: "rgba(255,255,255,0.5)", fontFamily: "'DM Mono', monospace", lineHeight: 1.5, margin: 0 },
  footer: { margin: "32px 0 0", fontSize: 11, color: "rgba(255,255,255,0.3)", opacity: 0.8, fontFamily: "'DM Mono', monospace", fontStyle: "italic", textAlign: "center", padding: "0 12px" }
};
